language: csharp  
sudo: required  
dist: trusty  
dotnet: 2.1
mono: none

branches:
  only:
  - master

script:  
  - bash "${TRAVIS_BUILD_DIR}/build/build.sh"

deploy:
  provider: script
  script: bash "${TRAVIS_BUILD_DIR}/build/deploy.sh"
  skip_cleanup: true
  on:
    branch: master